Patch: Fix V4L2 build in WebRTC for BSDs
Despite the name, Video-for-Linux is used on OpenBSD and FreeBSD as well.

As per `cmake/libwebrtcbuild.cmake`, all supported UNIX systems except Apple.

Fixes this:
```
.../src/modules/video_capture/linux/video_capture_linux.cc:63:16: error: no member named 'allow_v4l2' in 'webrtc::VideoCaptureOptions'
  if (options->allow_v4l2()) {
      ~~~~~~~  ^
1 error generated.
```